name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (pyflakes)
        run: python -m pyflakes src || true
      - name: Dry run (no real requests)
        run: |
          python -m src.main             --proxies proxies.example.txt             --twitter twitter.example.txt             --btc btc.example.txt             --experience experience.example.txt             --contribution contribution.example.txt             --why why.example.txt             --dry-run
